export const GET_ALL_TODO = 'GET_ALL_TODO';
export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';

export const GET_ALL_TODOS_SUCCESS = 'GET_ALL_TODOS_SUCCESS';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const COMPLETE_TODO_SUCCESS = 'COMPLETE_TODO_SUCCESS';

export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const CLEAR_TODOS = 'CLEAR_TODOS';
